spring:
  h2.console:
    enabled: true
    path: '/console'
  datasource:
    url: 'jdbc:h2:file:/Users/zegarlickit/IdeaProjects/nauka/ToDo-App/todo-db'
task:
  template:
    allow-multiple-task-from-template: false
